<a href="https://colab.research.google.com/github/mvaraujo1977/TechCahllenge_Tireoide/blob/Nirton_Afonso/model_tireoide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Junção dos dataset

In [ ]:
import pandas as pd

df = pd.read_csv("hypothyroid.data", header=None)

print(df.head())
print(df.shape)

            0   1  2  3  4  5  6  7  8  9   ... 16    17 18  19 20    21 22  \
0  hypothyroid  72  M  f  f  f  f  f  f  f  ...  y  0.60  y  15  y  1.48  y
1  hypothyroid  15  F  t  f  f  f  f  f  f  ...  y  1.70  y  19  y  1.13  y
2  hypothyroid  24  M  f  f  f  f  f  f  f  ...  y  0.20  y   4  y     1  y
3  hypothyroid  24  F  f  f  f  f  f  f  f  ...  y  0.40  y   6  y  1.04  y
4  hypothyroid  77  M  f  f  f  f  f  f  f  ...  y  1.20  y  57  y  1.28  y

   23 24 25
0  10  n  ?
1  17  n  ?
2   0  n  ?
3   6  n  ?
4  44  n  ?

[5 rows x 26 columns]
(3163, 26)

In [ ]:
import pandas as pd

# Carregando o arquivo principal
# Geralmente esses datasets vêm em partes (.data e .test),
# mas como temos o 'hypothyroid.data', vamos garantir que ele esteja bem estruturado.
df = pd.read_csv('hypothyroid.data', header=None, na_values='?')

# Se houver outro arquivo de dados similar, você pode concatená-los assim:
# df2 = pd.read_csv('outro_arquivo.data', header=None, na_values='?')
# df_final = pd.concat([df, df2], ignore_index=True)

print("Dataset carregado com sucesso!")
print(f"Formato do dataset: {df.shape}")
print(df.head())

Dataset carregado com sucesso!
Formato do dataset: (3163, 26)
            0     1  2  3  4  5  6  7  8  9   ... 16   17 18    19 20    21  \
0  hypothyroid  72.0  M  f  f  f  f  f  f  f  ...  y  0.6  y  15.0  y  1.48
1  hypothyroid  15.0  F  t  f  f  f  f  f  f  ...  y  1.7  y  19.0  y  1.13
2  hypothyroid  24.0  M  f  f  f  f  f  f  f  ...  y  0.2  y   4.0  y  1.00
3  hypothyroid  24.0  F  f  f  f  f  f  f  f  ...  y  0.4  y   6.0  y  1.04
4  hypothyroid  77.0  M  f  f  f  f  f  f  f  ...  y  1.2  y  57.0  y  1.28

  22    23 24  25
0  y  10.0  n NaN
1  y  17.0  n NaN
2  y   0.0  n NaN
3  y   6.0  n NaN
4  y  44.0  n NaN

[5 rows x 26 columns]

In [ ]:
import os

file_data = 'hypothyroid.data'
file_test = 'hypothyroid.test'

# Carrega o primeiro arquivo
df1 = pd.read_csv(file_data, header=None, na_values='?')

# Tenta carregar o segundo arquivo se existir
if os.path.exists(file_test):
    df2 = pd.read_csv(file_test, header=None, na_values='?')
    df_final = pd.concat([df1, df2], ignore_index=True)
    print(f"Arquivos combinados! Novo formato: {df_final.shape}")
else:
    df_final = df1
    print("Apenas o arquivo .data foi encontrado. df_final criado.")

print(df_final.head())

Apenas o arquivo .data foi encontrado. df_final criado.
            0     1  2  3  4  5  6  7  8  9   ... 16   17 18    19 20    21  \
0  hypothyroid  72.0  M  f  f  f  f  f  f  f  ...  y  0.6  y  15.0  y  1.48
1  hypothyroid  15.0  F  t  f  f  f  f  f  f  ...  y  1.7  y  19.0  y  1.13
2  hypothyroid  24.0  M  f  f  f  f  f  f  f  ...  y  0.2  y   4.0  y  1.00
3  hypothyroid  24.0  F  f  f  f  f  f  f  f  ...  y  0.4  y   6.0  y  1.04
4  hypothyroid  77.0  M  f  f  f  f  f  f  f  ...  y  1.2  y  57.0  y  1.28

  22    23 24  25
0  y  10.0  n NaN
1  y  17.0  n NaN
2  y   0.0  n NaN
3  y   6.0  n NaN
4  y  44.0  n NaN

[5 rows x 26 columns]

In [ ]:
import re

names_file = 'hypothyroid.names'

column_names = []

if os.path.exists(names_file):
    with open(names_file, 'r') as f:
        lines = f.readlines()

    # Tenta encontrar a linha que define as classes (primeira coluna)
    # No dataset hypothyroid, a primeira coluna geralmente é o alvo
    column_names.append('target')

    # Procura por padrões como 'nome_da_coluna: tipo.' no arquivo .names
    for line in lines:
        match = re.search(r'^([a-zA-Z0-9_ \-]+):', line)
        if match:
            col_name = match.group(1).strip().replace(' ', '_')
            if col_name not in column_names:
                column_names.append(col_name)

# Se conseguimos extrair nomes, aplicamos ao dataframe
if len(column_names) == len(df_final.columns):
    df_final.columns = column_names
    print("Nomes das colunas aplicados com sucesso!")
else:
    print(f"Aviso: Encontrados {len(column_names)} nomes para {len(df_final.columns)} colunas.")
    # Fallback manual baseado na estrutura padrão do dataset Hypothyroid da UCI
    uci_columns = [
        'target', 'age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
        'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
        'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
        'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH_measured', 'TSH',
        'T3_measured', 'T3', 'TT4_measured', 'TT4', 'T4U_measured', 'T4U',
        'FTI_measured', 'FTI', 'TBG_measured', 'TBG', 'referral_source'
    ]
    if len(df_final.columns) <= len(uci_columns):
        df_final.columns = uci_columns[:len(df_final.columns)]
        print("Colunas aplicadas usando mapeamento padrão UCI.")

display(df_final.head(15))

Nomes das colunas aplicados com sucesso!

,target,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,...,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG
0,hypothyroid,72.0,M,f,f,f,f,f,f,f,...,y,0.6,y,15.0,y,1.48,y,10.0,n,NaN
1,hypothyroid,15.0,F,t,f,f,f,f,f,f,...,y,1.7,y,19.0,y,1.13,y,17.0,n,NaN
2,hypothyroid,24.0,M,f,f,f,f,f,f,f,...,y,0.2,y,4.0,y,1.00,y,0.0,n,NaN
3,hypothyroid,24.0,F,f,f,f,f,f,f,f,...,y,0.4,y,6.0,y,1.04,y,6.0,n,NaN
4,hypothyroid,77.0,M,f,f,f,f,f,f,f,...,y,1.2,y,57.0,y,1.28,y,44.0,n,NaN
5,hypothyroid,85.0,F,f,f,f,f,t,f,f,...,y,1.1,y,27.0,y,1.19,y,23.0,n,NaN
6,hypothyroid,64.0,F,f,f,f,t,f,f,f,...,y,1.3,y,54.0,y,0.86,y,63.0,n,NaN
7,hypothyroid,72.0,F,f,f,f,f,f,f,f,...,y,1.9,y,34.0,y,1.05,y,32.0,n,NaN
8,hypothyroid,20.0,F,f,f,f,f,t,f,f,...,n,NaN,y,39.0,y,1.21,y,32.0,n,NaN
9,hypothyroid,42.0,F,f,f,f,f,f,f,f,...,n,NaN,y,7.6,y,1.02,y,7.5,n,NaN
10,hypothyroid,69.0,F,f,f,f,f,f,f,f,...,y,0.8,y,53.0,y,0.86,y,61.0,n,NaN
11,hypothyroid,75.0,F,f,f,f,f,f,f,f,...,y,1.1,y,38.0,y,0.92,y,41.0,n,NaN
12,hypothyroid,72.0,F,f,f,f,f,f,f,f,...,y,2.2,y,98.0,y,1.29,y,76.0,n,NaN
13,hypothyroid,53.0,F,f,f,f,f,f,t,f,...,y,1.5,y,44.0,y,0.98,y,45.0,n,NaN
14,hypothyroid,59.0,F,f,f,f,f,f,f,f,...,y,2.7,y,37.0,y,1.08,y,34.0,n,NaN

In [ ]:
df_final

,target,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,...,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG
0,hypothyroid,72.0,M,f,f,f,f,f,f,f,...,y,0.6,y,15.0,y,1.48,y,10.0,n,NaN
1,hypothyroid,15.0,F,t,f,f,f,f,f,f,...,y,1.7,y,19.0,y,1.13,y,17.0,n,NaN
2,hypothyroid,24.0,M,f,f,f,f,f,f,f,...,y,0.2,y,4.0,y,1.00,y,0.0,n,NaN
3,hypothyroid,24.0,F,f,f,f,f,f,f,f,...,y,0.4,y,6.0,y,1.04,y,6.0,n,NaN
4,hypothyroid,77.0,M,f,f,f,f,f,f,f,...,y,1.2,y,57.0,y,1.28,y,44.0,n,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3158,negative,58.0,F,f,f,f,f,f,f,f,...,y,1.7,y,86.0,y,0.91,y,95.0,n,NaN
3159,negative,29.0,F,f,f,f,f,f,f,f,...,y,1.8,y,99.0,y,1.01,y,98.0,n,NaN
3160,negative,77.0,M,f,f,f,f,f,f,f,...,y,0.6,y,71.0,y,0.68,y,104.0,n,NaN
3161,negative,74.0,F,f,f,f,f,f,f,f,...,y,0.1,y,65.0,y,0.48,y,137.0,n,NaN
3162,negative,56.0,F,t,f,f,f,f,f,f,...,y,1.8,y,139.0,y,0.97,y,143.0,n,NaN

In [ ]:
from google.colab import files

# Nome do arquivo de saída
output_filename = 'hypothyroid_final.csv'

# Salva o dataframe como CSV
df_final.to_csv(output_filename, index=False)

print(f'Arquivo {output_filename} gerado com sucesso! Iniciando download...')

# Faz o download do arquivo para o seu computador
files.download(output_filename)

Arquivo hypothyroid_final.csv gerado com sucesso! Iniciando download...